In [4]:
# Import the dependencies.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [5]:
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)

In [6]:
coords = zip(lats,lngs)
coordinates = list(coords)

In [7]:
from citipy import citipy

In [8]:
cities=[]

for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0],coordinate[1]).city_name
    if city not in cities:
        cities.append(city)

In [9]:
len(cities)

736

In [11]:
from config import api_key

In [12]:
link = "http://api.openweathermap.org/data/2.5/weather?units=Imperial"

url = link + "&appid=" + api_key

In [13]:
import requests

In [14]:
city_data= []


for i in cities:
    city_url = url + "&q=" + i.replace(" ","+")
    try:
        city_weather = requests.get(city_url).json()
        country = city_weather["sys"]["country"]
        lat = city_weather["coord"]["lat"]
        lon = city_weather["coord"]["lon"]
        max_temp = city_weather["main"]["temp_max"]
        humidity = city_weather["main"]["humidity"]
        cloudiness = city_weather["clouds"]["all"]
        wind_Speed = city_weather["wind"]["speed"]
        weather_desc = city_weather["weather"][0]["description"]
        
        city_data.append({"City": i.title(),
                          "Country": country,
                          "Lat": lat,
                          "Lon": lon,
                          "Max Temp": max_temp,
                          "Humidity" : humidity,
                          "Cloudiness" : cloudiness,
                          "Wind Speed" : wind_Speed,
                          "Weather description" : weather_desc})
    except Exception as error:
        print(error)

'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'
'sys'

In [15]:
city_data_df = pd.DataFrame(city_data)

In [16]:
city_data_df

,City,Country,Lat,Lon,Max Temp,Humidity,Cloudiness,Wind Speed,Weather description
0,Te Anau,NZ,-45.4167,167.7167,49.73,77,100,5.88,overcast clouds
1,Nizwa,OM,22.9333,57.5333,87.39,18,7,1.70,clear sky
2,Jamestown,US,42.0970,-79.2353,63.99,83,75,3.00,broken clouds
3,Albany,US,42.6001,-73.9662,69.03,88,88,3.00,overcast clouds
4,Slave Lake,CA,55.2834,-114.7690,58.98,55,90,13.80,overcast clouds
...,...,...,...,...,...,...,...,...,...
671,Mamou,GN,10.5000,-12.0000,71.02,91,14,1.77,few clouds
672,Uvarovo,RU,51.9849,42.2615,54.05,78,68,4.36,broken clouds
673,Cumberland,US,35.0502,-78.8664,84.70,59,20,9.22,few clouds
674,Vytegra,RU,61.0064,36.4481,44.06,96,100,6.44,overcast clouds
675,Skibbereen,IE,51.5500,-9.2667,48.00,92,100,10.29,light rain

In [18]:
x = city_data_df.to_csv("weatherPy_database.csv")